# Generated by Django 4.0.3 on 2022-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50)),
                ('received_from', models.CharField(max_length=255)),
                ('amount_in_words', models.CharField(max_length=500)),
                ('payment_for', models.CharField(max_length=255)),
                ('amount_in_figure', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
