# Generated by Django 4.0.3 on 2022-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
